### ISSUE TITLE
[BUG] AutoGL import frozen when the backend is PyG

### ISSUE THREAD

**Issue by TheLuminary** [THUMNLab/AutoGL#109]
the procedure of import frozen when the backend is selected as PyG.
When the backend is selected as DGL, the import of autogl is good.

**Environment (please complete the following information):**
 - GNU/Linux (kernel=5.10.131)
 - python version: 3.7.13
 - autogl version: branch of dev
 - Pytorch: 1.12
 - Pytorch-Geometric: 2.0.4
 - DGL: 0.9.0

**To Reproduce**
1. Run Python Interpreter with PyG backend selected: `AUTOGL_BACKEND=pyg python`.
2. Run `import autogl` in Python shell, then the is import is frozen.
3. Press `Ctrl + C` to interrupt the process and you may see the traces as follows.
4. See the logs.

**Trace**
Traceback (most recent call last):                                                                                                                                         
  File "backend.py", line 2, in <module>                                                                                                                                     
    import autogl                                                                                                                                                            
  File "/home/featurize/PycharmProjects/AutoGL-develop/AutoGL-dev/autogl/__init__.py", line 1, in <module>                                                                   
    from . import (                                                                                                                                                          
  File "/home/featurize/PycharmProjects/AutoGL-develop/AutoGL-dev/autogl/datasets/__init__.py", line 14, in <module>                                                         
    from ._ogb import (                                                                                                                                                      
  File "/home/featurize/PycharmProjects/AutoGL-develop/AutoGL-dev/autogl/datasets/_ogb.py", line 4, in <module>                                                              
    from ogb.nodeproppred import NodePropPredDataset                                                                                                                         
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/ogb/nodeproppred/__init__.py", line 1, in <module>
    from .evaluate import Evaluator
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/ogb/nodeproppred/evaluate.py", line 1, in <module>
    from sklearn.metrics import roc_auc_score
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/joblib/memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/joblib/_store_backends.py", line 15, in <module>
    from .backports import concurrency_safe_rename
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/joblib/backports.py", line 7, in <module>
    from distutils.version import LooseVersion
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 97, in find_spec
    return method()
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 108, in spec_for_distutils
    mod = importlib.import_module('setuptools._distutils')
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/environment/miniconda3/envs/AutoGL-develop/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 202, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 98, in acquire
KeyboardInterrupt

**Screenshots**
(omitted)

**Comment by jenghub** [comment]
Same issue here with PyTorch 1.13 and AutoGL 0.3.1. Any fixes? Would really like to try this library with PyG backend. Thanks!

**Comment by general502570** [comment]
Sorry for late response, the bug sometimes happens because importing `pkg_resources` in such case may cost very long time. There is a possible solution below:
1. Check if you can `import pkg_resources` directly in your environment.
2. If yes, write `import pkg_resources` at the beginning of the code you will run.
As such, `pkg_resources` will be imported in a fast way.
