### ISSUE TITLE
[OSError:[WinError 127]找不到指定的程序] pytorch-sparse安装引起

### ISSUE THREAD

**Issue by LandaChina** [THUMNLab/AutoGL#139]
**Describe the bug**
安装成功dgl和autogl后，import验证时报错，pytorch-sparse安装后python.exe无法找到入口，卸载pytorch-sparse又会提示不存在模块，问题在torch_sparse循环。

**To Reproduce**
1. import autogl
2. 先出现torch_sparse找不到问题，安装wheel
3. 成功后，import autogl
4. 再次错误:OSError: [WinError 127] 找不到指定的程序。
>>> import autogl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\datasets\__init__.py", line 14, in <module>
    from ._ogb import (
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\datasets\_ogb.py", line 8, in <module>
    from torch_sparse import SparseTensor
  File "C:\Users\llzhang\AppData\Roaming\Python\Python38\site-packages\torch_sparse\__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\torch\_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。
并且跳出警告，如下图：
![image](https://github.com/THUMNLab/AutoGL/assets/25998172/137b1f56-bef9-47aa-a933-dcf88af8a2d5)
无法定位程序输入点****于动态链接库****\torch_sparse\_version_cpu.pyd上

**Expected behavior**
成功import autogl，如何更好的安装torch_sparse，使之成功安装并且不报错。

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - python version: [3.8.17]
 - autogl version: [0.4.0]
 - pip list: [# packages in environment at C:\Users\All Users\anaconda3\envs\autogl:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
astor                     0.8.1                    pypi_0    pypi
autogl                    0.4.0                    pypi_0    pypi
bayesian-optimization     1.4.3                    pypi_0    pypi
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
ca-certificates           2023.05.30           haa95532_0    defaults
certifi                   2023.7.22        py38haa95532_0    defaults
cffi                      1.15.1           py38h2bbff1b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
chocolate                 0.0.2                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6            py38haa95532_0    defaults
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cryptography              41.0.2           py38hac1b9e3_0    defaults
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.14                  pypi_0    pypi
deeprobust                0.2.8                    pypi_0    pypi
dgl                       1.1.1                    py38_0    dglteam
dill                      0.3.7                    pypi_0    pypi
dnspython                 2.4.2                    pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.42.0                   pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
hyperopt                  0.1.2                    pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2    defaults
idna                      3.4              py38haa95532_0    defaults
imageio                   2.31.1                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.0.1                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319    defaults
jinja2                    3.1.2            py38haa95532_0    defaults
joblib                    1.3.2                    pypi_0    pypi
json-tricks               3.17.2                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
libffi                    3.4.4                hd77b12b_0    defaults
libuv                     1.44.2               h2bbff1b_0    defaults
lightgbm                  4.0.0                    pypi_0    pypi
littleutils               0.2.2                    pypi_0    pypi
llvmlite                  0.40.1                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46357    defaults
mkl-service               2.4.0            py38h2bbff1b_1    defaults
mkl_fft                   1.3.6            py38hf11a4ad_1    defaults
mkl_random                1.2.2            py38hf11a4ad_1    defaults
mpmath                    1.3.0            py38haa95532_0    defaults
netlsd                    1.0.2                    pypi_0    pypi
networkx                  3.1              py38haa95532_0    defaults
ninja                     1.10.2               haa95532_5    defaults
ninja-base                1.10.2               h6d14046_5    defaults
nni                       2.8                      pypi_0    pypi
numba                     0.57.1                   pypi_0    pypi
numpy                     1.24.3           py38h79a8e48_1    defaults
numpy-base                1.24.3           py38h8a87ada_1    defaults
ogb                       1.3.6                    pypi_0    pypi
openssl                   3.0.10               h2bbff1b_0    defaults
outdated                  0.2.2                    pypi_0    pypi
packaging                 23.0             py38haa95532_0    defaults
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1           py38haa95532_0    defaults
pooch                     1.4.0              pyhd3eb1b0_0    defaults
prettytable               3.8.0                    pypi_0    pypi
protobuf                  4.24.0                   pypi_0    pypi
psutil                    5.9.0            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pymongo                   4.4.1                    pypi_0    pypi
pyopenssl                 23.2.0           py38haa95532_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0    defaults
python                    3.8.17               h1aa4202_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pythonwebhdfs             0.2.3                    pypi_0    pypi
pytorch                   2.0.1           cpu_py38hb0bdfb8_0    defaults
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
requests                  2.31.0           py38haa95532_0    defaults
responses                 0.23.3                   pypi_0    pypi
schema                    0.7.5                    pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.10.1           py38hdcfc7df_1    defaults
setuptools                68.0.0           py38haa95532_0    defaults
simplejson                3.19.1                   pypi_0    pypi
smart-open                6.3.0                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0    defaults
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0    defaults
tensorboardx              2.6.2                    pypi_0    pypi
texttable                 1.6.7                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
torch-sparse              0.6.17+pt20cpu           pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.65.0           py38hd4e2768_0    defaults
typeguard                 4.1.0                    pypi_0    pypi
types-pyyaml              6.0.12.11                pypi_0    pypi
typing-extensions         4.7.1            py38haa95532_0    defaults
typing_extensions         4.7.1            py38haa95532_0    defaults
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.16          py38haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.6                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.38.4           py38haa95532_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
zipp                      3.16.2                   pypi_0    pypi
]

**Additional Info (Optional)**
![image](https://github.com/THUMNLab/AutoGL/assets/25998172/35cbbb66-b069-44a0-aa93-40a21a78fb65)
提示的定位不到的动态链接库_version_cpu，本地可以找到几个，替换报错位置的文档，也没有解决。

**Comment by LandaChina** [comment]
Additional Info:
Next, conda uninstall pytorch-scatter, successfully, the error 'OSError:[WinError 127]' happened again. Maybe the wrong is from the torch-sparse wheel installed.

**Comment by general502570** [comment]
谢谢您对AutoGL的关注。pytorch-sparse 的依赖应该是ogb数据集所需要的。您可以试一试能不能直接import ogb库。如果不能的话，请在ogb库的讨论区寻找相关解答。如果可以的话，请再回复给我们。

**Comment by LandaChina** [comment]
> 谢谢您对AutoGL的关注。pytorch-sparse 的依赖应该是ogb数据集所需要的。您可以试一试能不能直接import ogb库。如果不能的话，请在ogb库的讨论区寻找相关解答。如果可以的话，请再回复给我们。

成功import ogb！

(autogl) C:\Users\llzhang>python
Python 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ogb
>>> import autogl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\datasets\__init__.py", line 14, in <module>
    from ._ogb import (
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\autogl\datasets\_ogb.py", line 8, in <module>
    from torch_sparse import SparseTensor
  File "C:\Users\llzhang\AppData\Roaming\Python\Python38\site-packages\torch_sparse\__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\site-packages\torch\_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "C:\Users\All Users\anaconda3\envs\autogl\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。
>>>

但是import autogl还是存在以上问题。

**Comment by ZW-ZHANG** [comment]
感谢您的回复，该问题看起来是由于torch_sparse库引起的。您可以先试一下直接import torch_sparse能否成功，如过不能的话，请查看torch_sparse寻找相关原因（比如是否为python/torch/gpu版本与torch_sparse库不匹配等）

**Comment by LandaChina** [comment]
pytorch_sparse 是pytorch的1.6后版本使用，torch-sparse是1.6之前的版本，同时pytorch_sparse没有Windows版本，conda install找不到，从而得出的结论是autogl对操作系统有要求。

**Comment by ZW-ZHANG** [comment]
您好，可能之前没有说清，我说的是https://github.com/rusty1s/pytorch_sparse中的torch _sparse，它是pytorch geometric库的一个依赖（虽然您用的是DGL backend，但好像因为ogb或者别的库的依赖，也需要安装torch_sparse）。我个人尝试按照上面网页的说明安装torch_sparse后，是可以在windows下成功运行autogl
