### ISSUE TITLE
[BUG]v0.4.1 'DataFrame' has no attribute 'append'. Did you mean '_append'?

### ISSUE THREAD

**Issue by Gankuaidian** [THUMNLab/AutoGL#144]
**Describe the bug**
Traceback (most recent call last):
  File "/home/xxx/autoGL/ai1.py", line 6, in <module>
    custom_static_homogeneous_graph = GeneralStaticGraphGenerator.create_homogeneous_static_graph(
  File "/home/xxx/.pyenv/versions/3.10.13/lib/python3.10/site-packages/autogl-0.4.1-py3.10.egg/autogl/data/graph/_general_static_graph/_general_static_graph_generator.py", line 73, in create_homogeneous_static_graph
    _heterogeneous_edges_aggregation[('', '', '')] = (
  File "/home/xxx/.pyenv/versions/3.10.13/lib/python3.10/site-packages/autogl-0.4.1-py3.10.egg/autogl/data/graph/_general_static_graph/_general_static_graph_default_implementation.py", line 494, in __setitem__
    self._set_edges(edge_t, edges)
  File "/home/xxx/.pyenv/versions/3.10.13/lib/python3.10/site-packages/autogl-0.4.1-py3.10.egg/autogl/data/graph/_general_static_graph/_general_static_graph_default_implementation.py", line 683, in _set_edges
    self.__heterogeneous_edges_data_frame.append(
  File "/home/xxx/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pandas-2.1.4-py3.10-linux-x86_64.egg/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

**To Reproduce**
1. Use the provided example code from AutoGL documentation to produce a customized dataset
![image](https://github.com/THUMNLab/AutoGL/assets/123981809/f40c7a70-5351-410c-8308-807333822be1)

2. The pip installed old version does not have this problem.

After changing the line in the file" _general_static_graph_default_implementation.py", line 683, in _set_edges: 
    self.__heterogeneous_edges_data_frame.append(
into: 
    self.__heterogeneous_edges_data_frame._append(
there's no error message again.

**Comment by Martins6** [comment]
I had the same error! Commenting here for better visibility. The same code change, fixed it for me! Thanks, @Gankuaidian !
