### ISSUE TITLE
Performance check for refactored branch

### ISSUE THREAD

**Issue by Frozenmad** [THUMNLab/AutoGL#33]
@CoreLeader @lihy96 
Hi all, I've merged the `dev-szx/sampling-reproduction` into branch `refactor_test`, a copy of branch dev. And provide the performance check codes under benchmark.
@lihy96 Please help to run the comparison experiments on the new branch.
@CoreLeader I notice some bugs when running `pc_link_prediction_trainer.py`, The error message is:
```python
Traceback (most recent call last):
  File "pc_link_prediction_trainer.py", line 75, in <module>
    trainer.train(dataset, keep_valid_result=True)
  File "../autogl/module/train/link_prediction.py", line 270, in train
    self.train_only(data)
  File "../autogl/module/train/link_prediction.py", line 200, in train_only
    z = self.model.model.lp_encode(data)
  File "../autogl/module/model/gcn.py", line 228, in lp_encode
    data.x = self.__sequential_encoding_layers[i](data)
  File "/home/guancy/.pyenv/versions/miniconda3-4.3.30/envs/autograph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../autogl/module/model/gcn.py", line 54, in forward
    edge_weight: _typing.Optional[torch.Tensor] = getattr(data, "edge_weight")
AttributeError: 'Data' object has no attribute 'edge_weight'
```
Can you help fix this bug? You can fix the bug directly on this branch (refactor_test) since all the codes inside benchmark will be kept for future development. When the branch is ready, you can merge this to your dev branch~

**Comment by CoreLeader** [comment]
Already fix known bugs.

**Comment by Frozenmad** [comment]
Hi, there are other bugs comming when running `python pc_link_prediction_trainer.py` under `benchmark` folder. The log is:

```python
Traceback (most recent call last):
  File "pc_link_prediction_trainer.py", line 75, in <module>
    trainer.train(dataset, keep_valid_result=True)
  File "../autogl/module/train/link_prediction.py", line 270, in train
    self.train_only(data)
  File "../autogl/module/train/link_prediction.py", line 200, in train_only
    z = self.model.model.lp_encode(data)
  File "../autogl/module/model/gcn.py", line 228, in lp_encode
    data.x = self.__sequential_encoding_layers[i](data)
  File "/home/guancy/.pyenv/versions/miniconda3-4.3.30/envs/autograph/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../autogl/module/model/gcn.py", line 57, in forward
    raise TypeError
TypeError
```

Seems that current GNN layer cannot support customized edge_index?

**Comment by Frozenmad** [comment]
@CoreLeader @lihy96 
Thanks for your contribution! However, there still remains some bugs. Please fix them:

### [__Runtime bug__]
The sage will report the following bug when running:
```cmd
cd benchmark && python pc_link_prediction_trainer.py --model sage
```
error message
```python
Traceback (most recent call last):
  File "pc_link_prediction_trainer.py", line 75, in <module>
    trainer.train(dataset, keep_valid_result=True)
  File "../autogl/module/train/link_prediction.py", line 271, in train
    self.train_only(data)
  File "../autogl/module/train/link_prediction.py", line 223, in train_only
    val_loss = self.evaluate([data], mask="val", feval=feval)
  File "../autogl/module/train/link_prediction.py", line 420, in evaluate
    link_probs = self.predict_proba(dataset, mask)
  File "../autogl/module/train/link_prediction.py", line 324, in predict_proba
    z = self.predict_only(data)
  File "../autogl/module/train/link_prediction.py", line 249, in predict_only
    z = self.model.model.lp_encode(data)
  File "../autogl/module/model/graphsage.py", line 161, in lp_encode
    data.x = self.__sequential_encoding_layers[i](data)
  File "//python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../autogl/module/model/graphsage.py", line 54, in forward
    x: torch.Tensor = self._convolution.forward(x, edge_index)
  File "//python/lib/python3.6/site-packages/torch_geometric/nn/conv/sage_conv.py", line 63, in forward
    out = self.lin_l(out)
  File "//python/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "//python/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "//python/lib/python3.6/site-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

### [__performance bug__]
node classification: sage on cora becomes lower
link prediction: gcn on cora becomes lower

### Appendix
The full performance table:
#### [node classification on cora]
| branch | gcn| gat| sage|
|:---:|:---:|:---:|:---:|
| dev | 81.20 ~ 0.70  | 82.83 ~ 0.79  |  __78.45 ~ 1.59__ |
| refactor_test | 81.22 ~ 0.78 | 82.95 ~ 0.74 | __57.31 ~ 11.4__ |

#### [graph classification on mutag]
| branch | gin | topkpool|
|:---:|:---:|:---:|
| dev | 78.42 ~ 7.96  | 80.00 ~ 9.36 |
| refactor_test | 77.37 ~ 10.80 | 81.05 ~ 10.58 |

#### [link prediction on cora]
| branch | gcn| gat| sage|
|:---:|:---:|:---:|:---:|
| dev | __90.47 ~ 1.11__  | 90.67 ~ 0.98  |  88.69 ~ 1.23 |
| refactor_test | __86.65 ~ 0.86__ | 90.57 ~ 0.68 | __BUG__ |

**Comment by CoreLeader** [comment]
Sorry for late reply, I fixed the issue in GraphSAGE model, however, now there exists another issue, which may be caused by previous modification in link prediction trainer.
```
Traceback (most recent call last):
  File "/home/manjaro/Projects/PycharmProjects/AutoGL-development/AutoGL/benchmark/pc_link_prediction_trainer.py", line 75, in <module>
    trainer.train(dataset, keep_valid_result=True)
  File "/home/manjaro/Projects/PycharmProjects/AutoGL-development/AutoGL/autogl/module/train/link_prediction.py", line 270, in train
    data.edge_index = data.train_pos_edge_index
AttributeError: 'Data' object has no attribute 'train_pos_edge_index'
```
So I think @lihy96 may fix this consequent issue.

For the reduction of performance, I guess the reason is diverse default hyperparameters, I will read the `graphsage.py` and `gcn.py` in the two branchs carefully to discover the reason.

**Comment by CoreLeader** [comment]
Let's solve the performance reduction respectively.
https://github.com/THUMNLab/AutoGL/blob/fbd420e8e51098dfdcd179e75bd8dde9b19f17bc/autogl/module/model/gcn.py#L86-L94
First, for both GCN and GraphSAGE, from the above logic we can know following information
- The last transform layer is not adopted
- The second last layer does not have activation transform
Previously, I already notice the first point and drop the last layer in `lp_encode`, but did not notice the second difference.
Since each group of transforms (conv, act, dropout) have been wrapped into a wrapper class `_XXXLayer`, it's a little bit difficult to reproduce the second point. (The wrapped layer is significant for classification with sampling so I won't consider to abandon this technique)
My suggestions is used the `num_classes` argument in different way for link prediction, we can rename this argument as something like `output_dim`, which means the output dimension for encoding, and thus in this way the two tasks can utilize the models in a unified way, that is: The model will initialize `(len(hidden) + 1)` layers according to given `num_features`, `hidden`, `output_dim`, and `dropout` arguments, both tasks will utilize all the `(len(hidden) + 1)` layers for encoding, then decode with different decoding methods, i.e. `lp_decode` and `cls_decode`.
If this proposal is approved, I am willing to modify the two models. @Frozenmad

**Comment by Frozenmad** [comment]
Please fix the bugs following the discussions for now :).

**Comment by CoreLeader** [comment]
For now the known issues haven benn fixed, some results are as follows:
Node Classification with GraphSAGE: mean 0.7844700000000002 std 0.015964620258559246
Link prediction with GCN: mean 0.9028875990623954 std 0.011802572933489065

**Comment by Frozenmad** [comment]
All the performance checks are done. Thanks all for your contribution! @CoreLeader you can merge this branch into pr #31 now~
