### ISSUE TITLE
some wrong problems happened when i run the examples in source code with pycharm.

### ISSUE THREAD

**Issue by GorgeousWang** [THUMNLab/AutoGL#9]
run file:node_classification.py
*******begin: wrong information in python console******
WARNING:root:The OGB package is out of date. Your version is 1.2.3, while the latest version is 1.2.4.
Using backend: pytorch
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Traceback (most recent call last):
  File "D:/autocogdl/AutoGL-main/examples/node_classification.py", line 42, in <module>
    dataset = build_dataset_from_name(args.dataset)
  File "D:\autocogdl\AutoGL-main\autogl\datasets\__init__.py", line 118, in build_dataset_from_name
    dataset = DATASET_DICT[dataset_name](path)
  File "D:\autocogdl\AutoGL-main\autogl\datasets\pyg.py", line 60, in __init__
    Planetoid(path, dataset)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\datasets\planetoid.py", line 55, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\datasets\planetoid.py", line 105, in download
    download_url('{}/{}'.format(self.url, name), self.raw_dir)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\download.py", line 31, in download_url
    data = urllib.request.urlopen(url)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda3\envs\pytorch\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Process finished with exit code 1

************end******************

**Comment by Frozenmad** [comment]
It seems to be the network error when downloading datasets. Can you reach out the url shown in your error message?: 
https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x

If the network is ok, the bug should be resolved.

**Comment by GorgeousWang** [comment]
> It seems to be the network error when downloading datasets. Can you reach out the url shown in your error message?:
> https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
> 
> If the network is ok, the bug should be resolved.

thanks for your answer.
I can access this site through my browser but i can't ping it even through vpn.
could you upload the datas in this project or some alternative ways to download the data ? and then tell us where is the correct path to copy this data in .
 i think i am not the only one have this problem.
thanks for your help.

**Comment by GorgeousWang** [comment]
> It seems to be the network error when downloading datasets. Can you reach out the url shown in your error message?:
> https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
> 
> If the network is ok, the bug should be resolved.

thanks for your answer.
I can access this site through my browser but i can't ping it even through vpn.
could you upload the data in this project or some alternative ways to download the data ? and then tell us where is the correct path to copy this data in .
i think i am not the only one have this problem.
thanks for your help.

**Comment by Frozenmad** [comment]
Can you check and resolve the requirements  for dataset above @SwiftieH?

**Comment by Frozenmad** [comment]
> > It seems to be the network error when downloading datasets. Can you reach out the url shown in your error message?:
> > https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
> > If the network is ok, the bug should be resolved.
> 
> thanks for your answer.
> I can access this site through my browser but i can't ping it even through vpn.
> could you upload the data in this project or some alternative ways to download the data ? and then tell us where is the correct path to copy this data in .
> i think i am not the only one have this problem.
> thanks for your help.

(Method provided by @wondergo2017 ) It seems to be some network error about visiting Github. Can you try the method listed in https://github.com/521xueweihan/GitHub520 to see whether it can help?

**Comment by Frozenmad** [comment]
Since no response is received for too long, we will close this issue for now. Feel free to re-open if you have further problems & updates.
